---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      minecraft: 
        port: 25565
        expose: true
      bitcoind-p2p: 
        port: 8333
        expose: true
      electrs:
        port: 50001
        expose: true
      cln-p2p:
        port: 9735
        expose: true